# Generated by Django 4.1.4 on 2022-12-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_green', models.BooleanField()),
                ('full_blue', models.BooleanField()),
                ('full_red', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('token', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_sensor', models.BooleanField()),
                ('blue_sensor', models.BooleanField()),
                ('green_sensor', models.BooleanField()),
                ('proximity_sensor_1', models.BooleanField()),
                ('proximity_sensor_2', models.BooleanField()),
                ('proximity_sensor_3', models.BooleanField()),
                ('servomotor_1', models.BooleanField()),
                ('servomotor_2', models.BooleanField()),
                ('servomotor_3', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.container')),
            ],
        ),
    ]
